export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/login',
    REGISTER: '/api/register',
    REFRESH: '/api/refresh',
    LOGOUT: '/api/logout',
    ME: '/api/me',
    GENERATE_OTP: '/api/generate-otp',
    VALIDATE_OTP: '/api/validate-otp',
    UPDATE_PASSWORD: '/api/update-password',
    CHANGE_PASSWORD: '/api/change-password',
  },
  USERS: {
    GET_ALL: '/api/users',
    GET_BY_EMAIL: (email: string) => `/api/profile-details/${email}`,
    UPDATE: (email: string) => `/api/update/${email}`,
    ACTIVATE: '/api/updateActive',
    DEACTIVATE: '/api/updateDeactive',
    PROFILE_IMAGE: (email: string) => `/api/profile-image/${email}`,
  },
  JOBS: {
    GET_ALL: '/api/jobs/getPost',
    CREATE: '/api/jobs/post',
  },
  JOB_APPLICATIONS: {
    APPLY: '/api/job-applications/apply',
    UPDATE: '/api/job-applications/update',
    GET_BY_EMAIL: (email: string) => `/api/job-applications/${email}`,
    GET_BY_PREFIX: (prefix: string) => `/api/job-applications/byJobPrefix/${prefix}`,
    GET_BY_PREFIX_AND_EMAIL: (prefix: string, email: string) =>
      `/api/job-applications/byJobPrefixAndEmail/${prefix}/${email}`,
    FILTER_BY_PREFIX: (prefix: string) => `/api/job-applications/filterByPrefix/${prefix}`,
    SEND_ACK_MAIL: '/api/job-applications/send-ack-mail',
    SEND_REJECTION_MAIL: '/api/job-applications/send-rejection-mail',
    SEND_RECONFIRMATION_MAIL: '/api/job-applications/send-reconfirmation-mail',
    SEND_EXAM_LINK: '/api/job-applications/send-exam-link',
    SEND_SUCCESS_MAIL: '/api/job-applications/send-success-mail',
    SEND_FAILURE_MAIL: '/api/job-applications/send-failure-mail',
  },
  ASSESSMENTS: {
    UPLOAD: '/api/upload',
    ASSIGN: '/api/assign',
    ASSIGN_BLOB: '/api/assign-blob',
    GET_CONTENT: (id: number) => `/api/assessment-content/${id}`,
    GET_CANDIDATE_ASSESSMENTS: (email: string) => `/api/getCandidateAssessments/${email}`,
    SUBMIT: (id: number) => `/api/submit/${id}`,
    MARK_ATTENDED: '/api/markExamAttended',
    SAVE_RESULT: '/api/result',
    GET_RESULTS: '/api/get-results',
    GET_RESULTS_BY_JOB_PREFIX: '/api/get-results-by-job-prefix',
    GENERATE_QUESTIONS: '/api/generate-questions',
    GENERATE_CODING_QUESTIONS: '/api/generate-coding-questions',
    FETCH_QUESTIONS: (id: number) => `/api/fetchAssessment/${id}`,
  },
  INTERVIEWS: {
    ASSIGN: '/api/interview/assign-interview',
    ASSIGN_BULK: '/api/interview/assign-interview-bulk',
    GET_ACTIVE: '/api/interview/active',
    GET_RESULTS: '/api/interview/results',
    GET_RESULT_DETAIL: (id: number) => `/api/interview/results/${id}`,
  },
  AI: {
    START_INTERVIEW: '/api/interview/start',
    ANSWER_QUESTION: '/api/interview/answer',
    VOICE_TO_TEXT: '/api/interview/voice-to-text',
    UPLOAD_VIDEO: (scheduleId: number) => `/api/interview/${scheduleId}/video`,
    UPLOAD_SCREEN_RECORDING: (scheduleId: number) => `/api/interview/${scheduleId}/screen-recording`,
    VOICE_START: '/api/interview/voice/start',
    VOICE_END: (id: number) => `/api/interview/voice/${id}/end`,
    VOICE_STATUS: (id: number) => `/api/interview/voice/${id}/status`,
    VOICE_EVALUATION: (id: number) => `/api/interview/voice/${id}/evaluation`,
    VOICE_RESUME: (id: number) => `/api/interview/voice/${id}/resume`,
  },
  INTERVIEW_ADMIN: {
    STATS: '/api/interview/stats',
    PROCTORING_EVENTS: (id: number) => `/api/interview/${id}/proctoring-events`,
    CONVERSATION: (id: number) => `/api/interview/${id}/conversation`,
  },
  COMPILER: {
    RUN: '/api/compiler/run',
    SAVE_UNATTEMPTED: '/api/compiler/save-unattempted',
    RESULTS_CODE: '/api/compiler/results/code',
    RESULTS_BY_JOB_PREFIX: '/api/compiler/results/by-job-prefix',
  },
  RESUME: {
    UPLOAD: '/api/upload-resume',
    UPDATE: '/api/update-resume',
    VIEW: (email: string) => `/api/view-resume/${email}`,
    VIEW_ALL: '/api/view-all-resumes',
    UPLOAD_MULTIPLE: '/api/upload-resumes',
  },
  ATS: {
    SCREEN_SINGLE: '/api/ats/screen',
    SCREEN_BATCH: '/api/ats/screen-batch',
  },
  PROMPTS: {
    GET_BY_JOB: (prefix: string) => `/api/prompts/${prefix}`,
    SAVE: '/api/prompts',
    GET_EVALUATION_CATEGORIES: (prefix: string) => `/api/prompts/evaluation-categories/${prefix}`,
    SAVE_EVALUATION_CATEGORIES: '/api/prompts/evaluation-categories',
  },
} as const;
