export const PERMISSIONS = {
  USER_READ: 'USER_READ',
  USER_WRITE: 'USER_WRITE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  ASSESSMENT_READ: 'ASSESSMENT_READ',
  ASSESSMENT_WRITE: 'ASSESSMENT_WRITE',
  JOB_READ: 'JOB_READ',
  JOB_WRITE: 'JOB_WRITE',
  ATS_READ: 'ATS_READ',
  ATS_WRITE: 'ATS_WRITE',
  INTERVIEW_READ: 'INTERVIEW_READ',
  INTERVIEW_WRITE: 'INTERVIEW_WRITE',
  QUESTION_READ: 'QUESTION_READ',
  QUESTION_WRITE: 'QUESTION_WRITE',
  RESULT_READ: 'RESULT_READ',
  RESULT_WRITE: 'RESULT_WRITE',
  PROMPT_READ: 'PROMPT_READ',
  PROMPT_WRITE: 'PROMPT_WRITE',
} as const;

export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
