export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    ABOUT: '/about',
    CONTACT: '/contact',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    JOBS_CREATE: '/admin/jobs/create',
    CANDIDATES: '/admin/candidates',
    USERS: '/admin/users',
    ATS: '/admin/ats',
    ATS_BATCH: '/admin/ats/batch',
    ASSESSMENTS_ASSIGN: '/admin/assessments/assign',
    ASSESSMENTS_UPLOAD: '/admin/assessments/upload',
    ASSESSMENTS_RESULTS: '/admin/assessments/results',
    CANDIDATE_RESULT_DETAIL: '/admin/assessments/results/:jobPrefix/:email',
    INTERVIEWS_SCHEDULE: '/admin/interviews/schedule',
    INTERVIEWS_RESULTS: '/admin/interviews/results',
    PROMPTS: '/admin/prompts',
    PROFILE: '/admin/profile',
    CHANGE_PASSWORD: '/admin/change-password',
  },
  CANDIDATE: {
    DASHBOARD: '/candidate/dashboard',
    PROFILE: '/candidate/profile',
    CHANGE_PASSWORD: '/candidate/change-password',
    RESUME: '/candidate/resume',
    EVENTS: '/candidate/events',
    APPLICATIONS: '/candidate/applications',
    APPLY: '/candidate/apply',
    ASSESSMENTS: '/candidate/assessments',
    INSTRUCTIONS: '/candidate/instructions',
    EXAM_APTITUDE: '/candidate/exam/aptitude',
    EXAM_CODING: '/candidate/exam/coding',
    INTERVIEWS: '/candidate/interviews',
    INTERVIEW: '/candidate/interview',
    INTERVIEW_SUMMARY: '/candidate/interview/summary',
    RESULTS: '/candidate/results',
    RESULT_DETAIL: '/candidate/results/:id',
  },
  ERRORS: {
    UNAUTHORIZED: '/unauthorized',
    FORBIDDEN: '/forbidden',
  },
} as const;
