/**
 * Scripted question banks for the interview rehearsal.
 *
 * The live interview is generated by the AI over a websocket, against a
 * persisted schedule row whose ownership the server verifies. None of that can
 * run for a rehearsal, so Test Mode plays a fixed script instead: the questions
 * below are representative of what each phase asks, and are clearly labelled as
 * a script rather than passed off as the model's output.
 *
 * The phase names, budgets and question targets are copied from the backend's
 * `InterviewPhase` enum so the rehearsal reflects the real shape of a round.
 * If that enum changes, these numbers should follow it.
 */

export type InterviewPhaseId = 'TECHNICAL' | 'BEHAVIORAL';

export interface InterviewPhaseScript {
  id: InterviewPhaseId;
  /** `InterviewPhase.displayName` on the backend. */
  displayName: string;
  /** `InterviewPhase.durationMinutes`. */
  durationMinutes: number;
  /** `InterviewPhase.targetQuestions` — how many the AI aims to ask. */
  targetQuestions: number;
  /** `InterviewPhase.description`. */
  description: string;
  /** Where this phase sits in the full interview, for context on screen. */
  position: string;
  questions: string[];
}

export const INTERVIEW_SCRIPTS: Record<InterviewPhaseId, InterviewPhaseScript> = {
  TECHNICAL: {
    id: 'TECHNICAL',
    displayName: 'Technical',
    durationMinutes: 20,
    targetQuestions: 6,
    description: 'Role-specific technical questions',
    position: 'Phase 3 of 6, after Background and before Problem Solving',
    questions: [
      'Walk me through a system you have built end to end. What were the moving parts?',
      'How would you decide between a relational database and a document store for a new service?',
      'Describe how you would debug a request that is slow only in production.',
      'What does your testing look like on a feature you own — what do you test, and what do you deliberately not test?',
      'How do you keep an API backward compatible when the underlying model changes?',
      'Tell me about a technical decision you made that you would make differently now.',
    ],
  },
  BEHAVIORAL: {
    id: 'BEHAVIORAL',
    displayName: 'Behavioral',
    durationMinutes: 10,
    targetQuestions: 3,
    description: 'STAR format behavioral questions',
    position: 'Phase 5 of 6, after Problem Solving and before Closing',
    questions: [
      'Tell me about a time you disagreed with a decision your team made. What did you do?',
      'Describe a deadline you missed. What happened, and what changed afterwards?',
      'Give me an example of feedback that was hard to hear. How did you act on it?',
    ],
  },
};

/**
 * Said on screen wherever the scripted questions appear. The distinction
 * matters: an admin evaluating question quality must know they are reading a
 * fixed script, not this deployment's AI output.
 */
export const INTERVIEW_SCRIPT_NOTICE =
  'These questions come from a fixed script, not from the AI. A real interview generates each question from the candidate previous answer, so the wording and follow-ups will differ.';
